version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: movies_postgres
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
    container_name: movies_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/movies_db

volumnes:
  postgres_data