from fastapi import APIRouter
from app.agent.agent import agent
from app.agent.agent_schema import AgentRequest

router =  APIRouter()

@router.post("/agent")
def agent_chat(data: AgentRequest):

    """
        Main HTTP endpoint for the movie recommendation agent.

        Receives a user query with optional filters and preferences,
        and returns movie recommendations generated by the internal LangGraph pipeline.

        Args:
            data (AgentRequest): User request containing query, filters,
            top_k, and user mode.

        Returns:
            dict: Recommended movies along with the agent decision,
            applied filters, and user mode.
        """
    result = agent(
        user_input = data.query,
        top_k = data.top_k,
        filters = data.filters,
        user_mode = data.user_mode or "smart",
    )

    print("AGENT RESULT:", result)

    return {
        "query": result.get("query"),
        "action": result.get("action"),
        "movies": result.get("movies", []),
        "filters": result.get("filters", {}),
        "user_mode": result.get("user_mode")
    }


